const ipcData = [
    {
        chapter: 1,
        chapterName: "Introduction",
        sections: [
            { sectionNumber: '1', description: "Title and extent of operation of the Code." },
            { sectionNumber: '2', description: "Punishment of offenses committed within India." },
            { sectionNumber: '3', description: "Punishment of offenses committed beyond, but which by law may be tried within, India." },
            { sectionNumber: '4', description: "Extension of Code to extra-territorial offenses." },
            { sectionNumber: '5', description: "Certain laws not to be affected by this Act." }
        ]
    },    
    {
        chapter: 2,
        chapterName: "General Explanations",
        sections: [
            { sectionNumber: '6', description: "Definitions in the Code to be understood subject to exceptions." },
            { sectionNumber: '7', description: "Sense of expression once explained." },
            { sectionNumber: '8', description: "Gender." },
            { sectionNumber: '9', description: "Number." },
            { sectionNumber: '10', description: "Man, Woman." },
            { sectionNumber: '11', description: "Person." },
            { sectionNumber: '12', description: "Public." },
            { sectionNumber: '13', description: "Queen." },
            { sectionNumber: '14', description: "Servant of Government." },
            { sectionNumber: '15', description: "Definition of 'British India'." },
            { sectionNumber: '16', description: "'Government of India'." },
            { sectionNumber: '17', description: "'Government'." },
            { sectionNumber: '18', description: "'India'." },
            { sectionNumber: '19', description: "'Judge'." },
            { sectionNumber: '20', description: "'Court of Justice'." },
            { sectionNumber: '21', description: "'Public Servant'." },
            { sectionNumber: '22', description: "'Movable property'." },
            { sectionNumber: '23', description: "'Wrongful gain'." },
            { sectionNumber: '24', description: "'Dishonestly'." },
            { sectionNumber: '25', description: "'Fraudulently'." },
            { sectionNumber: '26', description: "'Reason to believe'." },
            { sectionNumber: '27', description: "'Property in possession of wife, clerk or servant'." },
            { sectionNumber: '28', description: "'Counterfeit'." },
            { sectionNumber: '29', description: "'Document'." },
            { sectionNumber: '29A', description: "'Electronic Record'." },
            { sectionNumber: '30', description: "'Valuable security'." },
            { sectionNumber: '31', description: "'A will'." },
            { sectionNumber: '32', description: "Words referring to acts include illegal omissions." },
            { sectionNumber: '33', description: "'Act', 'Omission'." },
            { sectionNumber: '34', description: "Acts done by several persons in furtherance of common intention." },
            { sectionNumber: '35', description: "When such an act is criminal by reason of its being done with a criminal knowledge or intention." },
            { sectionNumber: '36', description: "Effect caused partly by act and partly by omission." },
            { sectionNumber: '37', description: "Co-operation by doing one of several acts constituting an offense." },
            { sectionNumber: '38', description: "Persons concerned in criminal act may be guilty of different offenses." },
            { sectionNumber: '39', description: "'Voluntarily'." },
            { sectionNumber: '40', description: "'Offense'." },
            { sectionNumber: '41', description: "'Special law'." },
            { sectionNumber: '42', description: "'Local law'." },
            { sectionNumber: '43', description: "'Illegal', 'Legally bound to do'." },
            { sectionNumber: '44', description: "'Injury'." },
            { sectionNumber: '45', description: "'Life'." },
            { sectionNumber: '46', description: "'Death'." },
            { sectionNumber: '47', description: "'Animal'." },
            { sectionNumber: '48', description: "'Vessel'." },
            { sectionNumber: '49', description: "'Year', 'Month'." },
            { sectionNumber: '50', description: "'Section'." },
            { sectionNumber: '51', description: "'Oath'." },
            { sectionNumber: '52', description: "'Good faith'." }
        ]
    }, 
    {
        chapter: 3,
        chapterName: "Of Punishments",
        sections: [
            { sectionNumber: '53',  description: "Punishments." },
            { sectionNumber: '53A', description: "Construction of reference to transportation." },
            { sectionNumber: '54',  description: "Commutation of sentence of death." },
            { sectionNumber: '55',  description: "Commutation of sentence of imprisonment for life." },
            { sectionNumber: '55A', description: "Definition of appropriate Government." },
            { sectionNumber: '56',  description: "Sentence of Europeans and Americans to penal servitude." },
            { sectionNumber: '57',  description: "Fractions of terms of punishment." },
            { sectionNumber: '58',  description: "Offenders sentenced to transportation how dealt with until transported." },
            { sectionNumber: '59',  description: "Transportation instead of imprisonment." },
            { sectionNumber: '60',  description: "Sentence may be (in certain cases of imprisonment) wholly or partly rigorous or simple." },
            { sectionNumber: '61',  description: "[Repealed]" },
            { sectionNumber: '62',  description: "[Repealed]" },
            { sectionNumber: '63',  description: "Amount of fine." },
            { sectionNumber: '64',  description: "Sentence of imprisonment for non-payment of fine." },
            { sectionNumber: '65',  description: "Limit to imprisonment for non-payment of fine, when imprisonment and fine awardable." },
            { sectionNumber: '66',  description: "Description of imprisonment for non-payment of fine." },
            { sectionNumber: '67',  description: "Imprisonment for non-payment of fine, when offense punishable with fine only." },
            { sectionNumber: '68',  description: "Imprisonment to terminate on payment of fine." },
            { sectionNumber: '69',  description: "Termination of imprisonment on payment of proportional part of fine." },
            { sectionNumber: '70',  description: "Fine leviable within six years, or during imprisonment. Death not to discharge property from liability." },
            { sectionNumber: '71',  description: "Limit of punishment of offense made up of several offenses." },
            { sectionNumber: '72',  description: "Punishment of person guilty of one of several offenses, the judgment stating that it is doubtful of which." },
            { sectionNumber: '73',  description: "Solitary confinement." },
            { sectionNumber: '74',  description: "Limit of solitary confinement." },
            { sectionNumber: '75',  description: "Enhanced punishment for certain offenses under Chapter XII or Chapter XVII after previous conviction." }
        ]
    },    
    {
        chapter: 4,
        chapterName: "General Exceptions",
        sections: [
            { sectionNumber: '76', description: "Act done by a person bound, or by mistake of fact believing himself bound, by law." },
            { sectionNumber: '77', description: "Act of Judge when acting judicially." },
            { sectionNumber: '78', description: "Act done pursuant to the judgment or order of Court." },
            { sectionNumber: '79', description: "Act done by a person justified, or by mistake of fact believing himself justified, by law." },
            { sectionNumber: '80', description: "Accident in doing a lawful act." },
            { sectionNumber: '81', description: "Act likely to cause harm, but done without criminal intent, and to prevent other harm." },
            { sectionNumber: '82', description: "Act of a child under seven years of age." },
            { sectionNumber: '83', description: "Act of a child above seven and under twelve of immature understanding." },
            { sectionNumber: '84', description: "Act of a person of unsound mind." },
            { sectionNumber: '85', description: "Act of a person incapable of judgment by reason of intoxication caused against his will." },
            { sectionNumber: '86', description: "Offense requiring a particular intent or knowledge committed by one who is intoxicated." },
            { sectionNumber: '87', description: "Act not intended and not known to be likely to cause death or grievous hurt, done by consent." },
            { sectionNumber: '88', description: "Act not intended to cause death, done by consent in good faith for the person's benefit." },
            { sectionNumber: '89', description: "Act done in good faith for the benefit of a child or insane person, by or by consent of guardian." },
            { sectionNumber: '90', description: "Consent known to be given under fear or misconception." },
            { sectionNumber: '91', description: "Exclusion of acts which are offenses independently of harm caused." },
            { sectionNumber: '92', description: "Act done in good faith for benefit of a person without consent." },
            { sectionNumber: '93', description: "Communication made in good faith." },
            { sectionNumber: '94', description: "Act to which a person is compelled by threats." },
            { sectionNumber: '95', description: "Act causing slight harm." },
            { sectionNumber: '96', description: "Things done in private defense." },
            { sectionNumber: '97', description: "Right of private defense of the body and of property." },
            { sectionNumber: '98', description: "Right of private defense against the act of a person of unsound mind, etc." },
            { sectionNumber: '99', description: "Acts against which there is no right of private defense." },
            { sectionNumber: '100', description: "When the right of private defense of the body extends to causing death." },
            { sectionNumber: '101', description: "When such right extends to causing any harm other than death." },
            { sectionNumber: '102', description: "Commencement and continuance of the right of private defense of the body." },
            { sectionNumber: '103', description: "When the right of private defense of property extends to causing death." },
            { sectionNumber: '104', description: "When such right extends to causing any harm other than death." },
            { sectionNumber: '105', description: "Commencement and continuance of the right of private defense of property." },
            { sectionNumber: '106', description: "Right of private defense against deadly assault when there is risk of harm to an innocent person." }
        ]
    },    
    {
        chapter: 5,
        chapterName: "Of Abetment",
        sections: [
            { sectionNumber: '107', description: "Abetment of a thing." },
            { sectionNumber: '108', description: "Abettor." },
            { sectionNumber: '108A', description: "Abetment in India of offenses outside India." },
            { sectionNumber: '109', description: "Punishment of abetment if the act abetted is committed in consequence and where no express provision is made for its punishment." },
            { sectionNumber: '110', description: "Punishment of abetment if person abetted does act with different intention from that of abettor." },
            { sectionNumber: '111', description: "Liability of abettor when one act abetted and different act done." },
            { sectionNumber: '112', description: "Abettor when liable to cumulative punishment for act abetted and for act done." },
            { sectionNumber: '113', description: "Liability of abettor for an effect caused by the act abetted different from that intended by the abettor." },
            { sectionNumber: '114', description: "Abettor present when offense is committed." },
            { sectionNumber: '115', description: "Abetment of offense punishable with death or imprisonment for life—if offense not committed." },
            { sectionNumber: '116', description: "Abetment of offense punishable with imprisonment—if offense be not committed." },
            { sectionNumber: '117', description: "Abetting commission of offense by the public or by more than ten persons." },
            { sectionNumber: '118', description: "Concealing design to commit offense punishable with death or imprisonment for life." },
            { sectionNumber: '119', description: "Public servant concealing design to commit an offense which it is his duty to prevent." },
            { sectionNumber: '120', description: "Concealing design to commit offense punishable with imprisonment." }
        ]
    }, 
    {
        chapter: '5A',
        chapterName: "Criminal Conspiracy",
        sections: [
            { sectionNumber: '120A', description: "Definition of criminal conspiracy." },
            { sectionNumber: '120B', description: "Punishment of criminal conspiracy." }
        ]
    },       
    {
        chapter: 6,
        chapterName: "Of Offenses Against the State",
        sections: [
            { sectionNumber: '121', description: "Waging, or attempting to wage war, or abetting waging of war, against the Government of India." },
            { sectionNumber: '121A', description: "Conspiracy to commit offenses punishable by Section 121." },
            { sectionNumber: '122', description: "Collecting arms, etc., with intention of waging war against the Government of India." },
            { sectionNumber: '123', description: "Concealing with intent to facilitate design to wage war." },
            { sectionNumber: '124', description: "Assaulting President, Governor, etc., with intent to compel or restrain the exercise of any lawful power." },
            { sectionNumber: '124A', description: "Sedition." },
            { sectionNumber: '125', description: "Waging war against any Asiatic Power in alliance with the Government of India." },
            { sectionNumber: '126', description: "Committing depredation on territories of Power at peace with the Government of India." },
            { sectionNumber: '127', description: "Receiving property taken by war or depredation mentioned in Sections 125 and 126." },
            { sectionNumber: '128', description: "Public servant voluntarily allowing prisoner of State or war to escape." },
            { sectionNumber: '129', description: "Public servant negligently suffering such prisoner to escape." },
            { sectionNumber: '130', description: "Aiding escape of, or harboring such prisoner." }
        ]
    },
    {
        chapter: 6,
        chapterName: "Of Offenses Against the State",
        sections: [
            { sectionNumber: '131', description: "Abetting mutiny, or attempting to seduce a soldier, sailor or airman from his duty." },
            { sectionNumber: '132', description: "Abetment of mutiny, if mutiny is committed in consequence thereof." },
            { sectionNumber: '133', description: "Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office." },
            { sectionNumber: '134', description: "Abetment of such assault, if the assault is committed." },
            { sectionNumber: '135', description: "Abetment of desertion of soldier, sailor or airman." },
            { sectionNumber: '136', description: "Harboring deserter." },
            { sectionNumber: '137', description: "Deserter concealed on board merchant vessel through negligence of master." },
            { sectionNumber: '138', description: "Abetment of act of insubordination by soldier, sailor or airman." },
            { sectionNumber: '139', description: "Persons subject to certain Acts." },
            { sectionNumber: '140', description: "Wearing garb or carrying token used by soldier, sailor or airman." }
        ]
    },
    {
        chapter: 8,
        chapterName: "Of Offenses Against the Public Tranquility",
        sections: [
            { sectionNumber: '141', description: "Unlawful assembly." },
            { sectionNumber: '142', description: "Being member of unlawful assembly." },
            { sectionNumber: '143', description: "Punishment for being a member of an unlawful assembly." },
            { sectionNumber: '144', description: "Joining unlawful assembly armed with deadly weapon." },
            { sectionNumber: '145', description: "Joining or continuing in unlawful assembly, knowing it has been commanded to disperse." },
            { sectionNumber: '146', description: "Rioting." },
            { sectionNumber: '147', description: "Punishment for rioting." },
            { sectionNumber: '148', description: "Rioting, armed with deadly weapon." },
            { sectionNumber: '149', description: "Every member of unlawful assembly guilty of offense committed in prosecution of common object." },
            { sectionNumber: '150', description: "Hiring, or conniving at hiring, of persons to join unlawful assembly." },
            { sectionNumber: '151', description: "Knowingly joining or continuing in assembly of five or more persons after it has been commanded to disperse." },
            { sectionNumber: '152', description: "Assaulting or obstructing public servant when suppressing riot, etc." },
            { sectionNumber: '153', description: "Wantonly giving provocation with intent to cause riot—if rioting be committed—if not committed." },
            { sectionNumber: '153A', description: "Promoting enmity between different groups on grounds of religion, race, place of birth, residence, language, etc., and doing acts prejudicial to maintenance of harmony." },
            { sectionNumber: '153B', description: "Imputations, assertions prejudicial to national-integration." },
            { sectionNumber: '154', description: "Owner or occupier of land on which an unlawful assembly is held." },
            { sectionNumber: '155', description: "Liability of person for whose benefit riot is committed." },
            { sectionNumber: '156', description: "Liability of agent of owner or occupier for whose benefit riot is committed." },
            { sectionNumber: '157', description: "Harboring persons hired for an unlawful assembly." },
            { sectionNumber: '158', description: "Being hired to take part in an unlawful assembly or riot." },
            { sectionNumber: '159', description: "Affray." },
            { sectionNumber: '160', description: "Punishment for committing affray." }
        ]
    },    
    {
        chapter: 9,
        chapterName: "Of Offenses by or Relating to Public Servants",
        sections: [
            { sectionNumber: '161', description: "[Repealed]" },
            { sectionNumber: '162', description: "[Repealed]" },
            { sectionNumber: '163', description: "[Repealed]" },
            { sectionNumber: '164', description: "[Repealed]" },
            { sectionNumber: '165', description: "[Repealed]" },
            { sectionNumber: '166', description: "Public servant disobeying law, with intent to cause injury to any person." },
            { sectionNumber: '167', description: "Public servant framing an incorrect document with intent to cause injury." },
            { sectionNumber: '168', description: "Public servant unlawfully engaging in trade." },
            { sectionNumber: '169', description: "Public servant unlawfully buying or bidding for property." },
            { sectionNumber: '170', description: "Personating a public servant." },
            { sectionNumber: '171', description: "Wearing garb or carrying token used by public servant with fraudulent intent." }
        ]
    },
    {
        chapter: '9A',
        chapterName: "Of Offenses Relating to Elections",
        sections: [
            { sectionNumber: '171A', description: "Definitions." },
            { sectionNumber: '171B', description: "Bribery." },
            { sectionNumber: '171C', description: "Undue influence at elections." },
            { sectionNumber: '171D', description: "Personation at elections." },
            { sectionNumber: '171E', description: "Punishment for bribery." },
            { sectionNumber: '171F', description: "Punishment for undue influence or personation at an election." },
            { sectionNumber: '171G', description: "False statement in connection with an election." },
            { sectionNumber: '171H', description: "Illegal payments in connection with an election." },
            { sectionNumber: '171I', description: "Failure to keep election accounts." }
        ]
    },
    {
        chapter: 10,
        chapterName: "Of Contempts of the Lawful Authority of Public Servants",
        sections: [
            { sectionNumber: "172", description: "Failure to assist a public servant when required." },
            { sectionNumber: "173", description: "Preventing a public servant from discharging their duty." },
            { sectionNumber: "174", description: "Non-attendance in obedience to an order from a public servant." },
            { sectionNumber: "175", description: "Refusing to sign a document when ordered by a public servant." },
            { sectionNumber: "176", description: "Omission to give notice or information to a public servant." },
            { sectionNumber: "177", description: "Furnishing false information to a public servant." },
            { sectionNumber: "178", description: "Refusing to answer questions asked by a public servant." },
            { sectionNumber: "179", description: "Refusing to produce a document or electronic record when required by a public servant." },
            { sectionNumber: "180", description: "Refusing to sign a document or electronic record required by a public servant." },
            { sectionNumber: "181", description: "Refusing to take an oath or affirmation when required by a public servant." },
            { sectionNumber: "182", description: "Giving false information to a public servant with intent to cause harm." },
            { sectionNumber: "183", description: "Obstructing a public servant in the discharge of their duty." },
            { sectionNumber: "184", description: "Giving false information to a public servant intending to cause injury." },
            { sectionNumber: "185", description: "False statement made in evidence." },
            { sectionNumber: "186", description: "Obstructing a public servant in discharge of their duties." },
            { sectionNumber: "187", description: "False statement made to a public servant." },
            { sectionNumber: "188", description: "Disobedience to an order promulgated by a public servant." },
            { sectionNumber: "189", description: "Threatening a public servant with injury." },
            { sectionNumber: "190", description: "Falsely alleging offenses or misconduct against a public servant." }
        ]
    },
    {
        chapter: 11,
        chapterName: "Of False Evidence and Offenses Against Public Justice",
        sections: [
            { sectionNumber: "191", description: "False evidence given in judicial proceedings." },
            { sectionNumber: "192", description: "Fabrication of false evidence." },
            { sectionNumber: "193", description: "Punishment for false evidence." },
            { sectionNumber: "194", description: "False evidence with intent to procure a conviction." },
            { sectionNumber: "195", description: "Providing false information to a public servant." },
            { sectionNumber: "196", description: "Using false evidence with intent to deceive." },
            { sectionNumber: "197", description: "Prosecuting a person based on false evidence." },
            { sectionNumber: "198", description: "False evidence presented to a court." },
            { sectionNumber: "199", description: "Punishment for false evidence given in court." },
            { sectionNumber: "200", description: "Receiving false evidence." },
            { sectionNumber: "201", description: "Concealing evidence in judicial proceedings." },
            { sectionNumber: "202", description: "Fabricating false evidence." },
            { sectionNumber: "203", description: "Obstructing justice by hiding evidence." },
            { sectionNumber: "204", description: "Interference with evidence." },
            { sectionNumber: "205", description: "Misleading a public servant with false evidence." },
            { sectionNumber: "206", description: "Corruption in judicial proceedings." },
            { sectionNumber: "207", description: "False information provided to judicial authorities." },
            { sectionNumber: "208", description: "Concealment of evidence in judicial proceedings." },
            { sectionNumber: "209", description: "False claims made in court." },
            { sectionNumber: "210", description: "Abetment of false evidence." },
            { sectionNumber: "211", description: "Compounding offenses related to false evidence." },
            { sectionNumber: "212", description: "Punishment for fabricating evidence." },
            { sectionNumber: "213", description: "Concealing offenses or misconduct." },
            { sectionNumber: "214", description: "Interfering with legal investigations." },
            { sectionNumber: "215", description: "Misuse of legal authority to suppress evidence." },
            { sectionNumber: "216", description: "False statements in legal procedures." },
            { sectionNumber: "217", description: "Punishment for giving false evidence." },
            { sectionNumber: "218", description: "False claims and accusations." },
            { sectionNumber: "219", description: "Corruption and bribery affecting justice." },
            { sectionNumber: "220", description: "Obstruction of justice by false evidence." },
            { sectionNumber: "221", description: "Failure to report false evidence." },
            { sectionNumber: "222", description: "Complicity in fabricating evidence." },
            { sectionNumber: "223", description: "Interference in judicial proceedings." },
            { sectionNumber: "224", description: "False testimonies in court." },
            { sectionNumber: "225", description: "Punishment for misleading justice." },
            { sectionNumber: "226", description: "Fabrication of false documents for court." },
            { sectionNumber: "227", description: "Tampering with evidence." },
            { sectionNumber: "228", description: "Misrepresentation in judicial statements." },
            { sectionNumber: "229", description: "Consequences of providing false information to courts." }
        ]
    },        
    {
        chapter: 12,
        chapterName: "Of Offenses Relating to the Administration of Justice",
        sections: [
            { sectionNumber: "230", description: "Offenses related to the administration of justice." },
            { sectionNumber: "231", description: "Interference with court proceedings." },
            { sectionNumber: "232", description: "Obstruction of justice by misleading authorities." },
            { sectionNumber: "233", description: "False claims affecting judicial decisions." },
            { sectionNumber: "234", description: "Refusal to cooperate with judicial investigations." },
            { sectionNumber: "235", description: "Tampering with judicial records." },
            { sectionNumber: "236", description: "Misrepresentation in legal documents." },
            { sectionNumber: "237", description: "Corruption in legal processes." },
            { sectionNumber: "238", description: "Fabrication of legal evidence." },
            { sectionNumber: "239", description: "False testimonies in court." },
            { sectionNumber: "240", description: "Abuse of judicial authority." },
            { sectionNumber: "241", description: "Failure to provide truthful evidence." },
            { sectionNumber: "242", description: "Interference with legal procedures." },
            { sectionNumber: "243", description: "Unlawful actions affecting justice administration." },
            { sectionNumber: "244", description: "Misuse of legal authority." },
            { sectionNumber: "245", description: "False representation in legal contexts." },
            { sectionNumber: "246", description: "Obstructing justice by false claims." },
            { sectionNumber: "247", description: "Consequences of misleading legal authorities." },
            { sectionNumber: "248", description: "Manipulation of court processes." },
            { sectionNumber: "249", description: "Punishment for obstruction of justice." },
            { sectionNumber: "250", description: "Interference in legal investigations." },
            { sectionNumber: "251", description: "False statements affecting judicial outcomes." },
            { sectionNumber: "252", description: "Legal consequences of providing false information." },
            { sectionNumber: "253", description: "Fabricating evidence for court proceedings." },
            { sectionNumber: "254", description: "Misrepresentation of judicial facts." },
            { sectionNumber: "255", description: "False claims related to legal cases." },
            { sectionNumber: "256", description: "Obstruction by misrepresentation." },
            { sectionNumber: "257", description: "Corruption impacting judicial fairness." },
            { sectionNumber: "258", description: "Consequences of obstructing justice." },
            { sectionNumber: "259", description: "Unlawful influence on legal decisions." },
            { sectionNumber: "260", description: "Punishment for false evidence in legal contexts." },
            { sectionNumber: "261", description: "Consequences of misleading court proceedings." },
            { sectionNumber: "262", description: "Legal consequences of tampering with evidence." },
            { sectionNumber: "263", description: "Abuse of legal authority in court processes." }
        ]
    },
    {
        chapter: 13,
        chapterName: "Of Offenses Relating to Weight and Measures",
        sections: [
            { sectionNumber: "418", description: "Cheating by Personation" },
            { sectionNumber: "419", description: "Punishment for Cheating by Personation" },
            { sectionNumber: "420", description: "Cheating and Dishonestly Inducing Delivery of Property" },
            { sectionNumber: "421", description: "Dishonest or Fraudulent Removal or Concealment of Property" },
            { sectionNumber: "422", description: "Dishonest or Fraudulent Disposal of Property" },
            { sectionNumber: "423", description: "Dishonest or Fraudulent Conveyance of Property" },
            { sectionNumber: "424", description: "Dishonest or Fraudulent Removal of Property" },
            { sectionNumber: "425", description: "Mischief" },
            { sectionNumber: "426", description: "Punishment for Mischief" },
            { sectionNumber: "427", description: "Mischief Causing Damage to the Amount of Fifty Rupees" }
        ]
    },    
    {
        chapter: 14,
        chapterName: "Of Offenses Affecting the Public Health, Safety, Convenience, Decency and Morals",
        sections: [
            { sectionNumber: "268", description: "Public Nuisance" },
            { sectionNumber: "269", description: "Negligent Act Likely to Spread Infection of Disease Dangerous to Life" },
            { sectionNumber: "270", description: "Malignant Act Likely to Spread Infection of Disease Dangerous to Life" },
            { sectionNumber: "271", description: "Disobedience to Quarantine Rule" },
            { sectionNumber: "272", description: "Adulteration of Food or Drink Intended for Sale" },
            { sectionNumber: "273", description: "Sale of Noxious Food or Drink" },
            { sectionNumber: "274", description: "Adulteration of Drugs" },
            { sectionNumber: "275", description: "Sale of Adulterated Drugs" },
            { sectionNumber: "276", description: "Sale of Adulterated Drugs as Genuine" },
            { sectionNumber: "277", description: "Making the Water Contaminated" },
            { sectionNumber: "278", description: "Making the Atmosphere Unfit for Human Habitation" },
            { sectionNumber: "279", description: "Rash Driving or Riding on a Public Way" },
            { sectionNumber: "280", description: "Rash Navigation or Conduct in the Water" },
            { sectionNumber: "281", description: "Disobedience to Orders Regarding Navigation" },
            { sectionNumber: "282", description: "Conveying to Another Person the Effect of One’s Conduct" },
            { sectionNumber: "283", description: "Danger or Obstruction in Public Way or Navigation" },
            { sectionNumber: "284", description: "Negligent Conduct with Respect to Poison or Noxious Substance" },
            { sectionNumber: "285", description: "Negligent Conduct with Respect to Fire or Combustible Matter" },
            { sectionNumber: "286", description: "Negligent Conduct with Respect to Explosive Substance" },
            { sectionNumber: "287", description: "Negligent Conduct with Respect to Machinery" },
            { sectionNumber: "288", description: "Negligent Conduct with Respect to Any Structure" },
            { sectionNumber: "289", description: "Negligent Conduct with Respect to Animals" },
            { sectionNumber: "290", description: "Public Nuisance" },
            { sectionNumber: "291", description: "Continuing Public Nuisance" },
            { sectionNumber: "292", description: "Sale, etc., of Obscene Books, etc." },
            { sectionNumber: "293", description: "Sale, etc., of Obscene Objects to Young Persons" },
            { sectionNumber: "294", description: "Obscene Acts and Songs" }
        ]
    },    
    {
        chapter: 15,
        chapterName: "Of Offenses Relating to Religion",
        sections: [
            { sectionNumber: "295", description: "Injuring or defiling place of worship with intent to insult the religion of any class" },
            { sectionNumber: "295A", description: "Deliberate and malicious acts intended to outrage religious feelings" },
            { sectionNumber: "296", description: "Disturbing religious assembly" },
            { sectionNumber: "297", description: "Trespassing on burial places, etc." },
            { sectionNumber: "298", description: "Uttering words, etc., with deliberate intent to wound religious feelings" },
            { sectionNumber: "299", description: "Action likely to cause breach of peace by religious mischief" }
        ]
    },       
    {
        chapter: 16,
        chapterName: "Of Offenses by or Relating to Government Officials",
        sections: [
            { sectionNumber: "299", description: "Culpable Homicide" },
            { sectionNumber: "300", description: "Murder" },
            { sectionNumber: "301", description: "Murder by One Person or Several Persons" },
            { sectionNumber: "302", description: "Punishment for Murder" },
            { sectionNumber: "303", description: "Punishment for Murder by a Convict under Sentence of Life Imprisonment" },
            { sectionNumber: "304", description: "Punishment for Culpable Homicide not Amounting to Murder" },
            { sectionNumber: "305", description: "Abetment of Suicide of a Child or Insane Person" },
            { sectionNumber: "306", description: "Abetment of Suicide" },
            { sectionNumber: "307", description: "Attempt to Murder" },
            { sectionNumber: "308", description: "Attempt to Commit Culpable Homicide" },
            { sectionNumber: "309", description: "Attempt to Commit Suicide" },
            { sectionNumber: "310", description: "Attempt to Commit Murder by a Person under Sentence of Life Imprisonment" },
            { sectionNumber: "311", description: "Punishment for Voluntarily Causing Hurt" },
            { sectionNumber: "312", description: "Causing Hurt by Means of Poison" },
            { sectionNumber: "313", description: "Causing Hurt with Intent to Commit Offense" },
            { sectionNumber: "314", description: "Voluntarily Causing Hurt to Extort Property" },
            { sectionNumber: "315", description: "Act Done with Intent to Prevent Child from Being Born Alive or to Cause it to Die After Birth" },
            { sectionNumber: "316", description: "Causing Death of Quick Child by Act Done with Intent" },
            { sectionNumber: "317", description: "Exposure and Abandonment of Child" },
            { sectionNumber: "318", description: "Concealment of Birth by Secret Disposal of Dead Body" },
            { sectionNumber: "319", description: "Hurt" },
            { sectionNumber: "320", description: "Grievous Hurt" },
            { sectionNumber: "321", description: "Voluntarily Causing Hurt" },
            { sectionNumber: "322", description: "Punishment for Voluntarily Causing Grievous Hurt" },
            { sectionNumber: "323", description: "Punishment for Voluntarily Causing Hurt" },
            { sectionNumber: "324", description: "Voluntarily Causing Hurt by Dangerous Weapons or Means" },
            { sectionNumber: "325", description: "Punishment for Voluntarily Causing Grievous Hurt" },
            { sectionNumber: "326", description: "Voluntarily Causing Grievous Hurt by Dangerous Weapons or Means" },
            { sectionNumber: "327", description: "Voluntarily Causing Hurt to Extort Property" },
            { sectionNumber: "328", description: "Causing Hurt by Means of Poison with Intent to Commit Offense" },
            { sectionNumber: "329", description: "Voluntarily Causing Hurt to Extort Property" },
            { sectionNumber: "330", description: "Voluntarily Causing Hurt to Extort Property or Compel Restoration" },
            { sectionNumber: "331", description: "Voluntarily Causing Hurt to Compel Restoration" },
            { sectionNumber: "332", description: "Voluntarily Causing Hurt to a Public Servant" },
            { sectionNumber: "333", description: "Voluntarily Causing Hurt to a Public Servant Engaged in Discharge of Duty" },
            { sectionNumber: "334", description: "Voluntarily Causing Hurt on Provocation" },
            { sectionNumber: "335", description: "Punishment for Voluntarily Causing Hurt on Provocation" },
            { sectionNumber: "336", description: "Act Endangering Life or Personal Safety of Others" },
            { sectionNumber: "337", description: "Causing Hurt by Act Endangering Life or Personal Safety of Others" },
            { sectionNumber: "338", description: "Causing Grievous Hurt by Act Endangering Life or Personal Safety of Others" },
            { sectionNumber: "339", description: "Wrongful Confinement" },
            { sectionNumber: "340", description: "Punishment for Wrongful Confinement" },
            { sectionNumber: "341", description: "Punishment for Wrongful Restraint" },
            { sectionNumber: "342", description: "Punishment for Wrongful Confinement" },
            { sectionNumber: "343", description: "Wrongful Confinement for Three or More Days" },
            { sectionNumber: "344", description: "Wrongful Confinement for One or Two Days" },
            { sectionNumber: "345", description: "Wrongful Confinement in Secret" },
            { sectionNumber: "346", description: "Wrongful Confinement in a Place of Cruelty" },
            { sectionNumber: "347", description: "Wrongful Confinement to Extort Property or Compel Restoration" },
            { sectionNumber: "348", description: "Wrongful Confinement to Extort Property or Compel Restoration" },
            { sectionNumber: "349", description: "Force Used to Cause Wrongful Confinement" },
            { sectionNumber: "350", description: "Assault" },
            { sectionNumber: "351", description: "Assault" },
            { sectionNumber: "352", description: "Assault or Criminal Force" },
            { sectionNumber: "353", description: "Assault or Criminal Force to Prevent Public Servant from Discharging Duty" },
            { sectionNumber: "354", description: "Assault or Criminal Force to Woman with Intent to Outrage Her Modesty" },
            { sectionNumber: "355", description: "Assault or Criminal Force with Intent to Dishonor Person" },
            { sectionNumber: "356", description: "Assault or Criminal Force with Intent to Commit Theft" },
            { sectionNumber: "357", description: "Assault or Criminal Force with Intent to Commit Rape" },
            { sectionNumber: "358", description: "Assault or Criminal Force with Intent to Commit Rape" },
            { sectionNumber: "359", description: "Kidnapping" },
            { sectionNumber: "360", description: "Kidnapping from India" },
            { sectionNumber: "361", description: "Kidnapping from Legal Guardianship" },
            { sectionNumber: "362", description: "Abduction" },
            { sectionNumber: "363", description: "Kidnapping from Legal Guardianship" },
            { sectionNumber: "364", description: "Kidnapping or Abducting with Intent to Murder" },
            { sectionNumber: "365", description: "Kidnapping or Abducting with Intent to Secretly and Wrongfully Constrain" },
            { sectionNumber: "366", description: "Kidnapping, Abducting or Inducing Woman to compel her Marriage" },
            { sectionNumber: "367", description: "Kidnapping, Abducting or Inducing Woman to Cause her to be Forced or Seduced to Illicit Intercourse" },
            { sectionNumber: "368", description: "Wrongfully Concealing or Keeping in Secret" },
            { sectionNumber: "369", description: "Kidnapping or Abducting a Child with Intent to Steal" },
            { sectionNumber: "370", description: "Trafficking of Persons" },
            { sectionNumber: "371", description: "Buying or Selling of Slaves" },
            { sectionNumber: "372", description: "Selling of Minor for Immoral Purposes" },
            { sectionNumber: "373", description: "Buying of Minor for Immoral Purposes" },
            { sectionNumber: "374", description: "Unlawful Compulsion for Forced Labour" },
            { sectionNumber: "375", description: "Rape" },
            { sectionNumber: "376", description: "Punishment for Rape" },
            { sectionNumber: "377", description: "Unnatural Offenses" }
        ]
    },    
    {
        chapter: 17,
        chapterName: "Of Offenses Relating to Judicial Proceedings",
        sections: [
            { sectionNumber: "378", description: "Contempt of court." },
            { sectionNumber: "379", description: "Interference with judicial proceedings." },
            { sectionNumber: "380", description: "Obstruction of justice in court matters." },
            { sectionNumber: "381", description: "Misrepresentation in judicial contexts." },
            { sectionNumber: "382", description: "Failure to comply with court orders." },
            { sectionNumber: "383", description: "Misuse of judicial authority." },
            { sectionNumber: "384", description: "Fabrication of court evidence." },
            { sectionNumber: "385", description: "False statements in court." },
            { sectionNumber: "386", description: "Contempt and obstruction in judicial processes." },
            { sectionNumber: "387", description: "Interference with legal proceedings." },
            { sectionNumber: "388", description: "False representation in judicial matters." },
            { sectionNumber: "389", description: "Corruption affecting judicial outcomes." },
            { sectionNumber: "390", description: "Failure to provide truthful evidence in court." },
            { sectionNumber: "391", description: "Illegal actions impacting court proceedings." },
            { sectionNumber: "392", description: "Obstructing justice through false claims." },
            { sectionNumber: "393", description: "Misuse of judicial processes." },
            { sectionNumber: "394", description: "False claims affecting court decisions." },
            { sectionNumber: "395", description: "Tampering with court records." },
            { sectionNumber: "396", description: "Contempt of court orders." },
            { sectionNumber: "397", description: "Legal consequences of obstructing justice." },
            { sectionNumber: "398", description: "Failure to comply with judicial procedures." },
            { sectionNumber: "399", description: "Corruption in judicial processes." },
            { sectionNumber: "400", description: "False evidence presented to courts." },
            { sectionNumber: "401", description: "Interference with legal investigations." },
            { sectionNumber: "402", description: "Misrepresentation in legal proceedings." },
            { sectionNumber: "403", description: "Contempt of legal authority." },
            { sectionNumber: "404", description: "Failure to comply with legal directives." },
            { sectionNumber: "405", description: "Obstructing justice through false statements." },
            { sectionNumber: "406", description: "Corruption impacting legal outcomes." },
            { sectionNumber: "407", description: "Fabrication of evidence in judicial proceedings." },
            { sectionNumber: "408", description: "Contempt and legal consequences." },
            { sectionNumber: "409", description: "Failure to follow court orders." },
            { sectionNumber: "410", description: "Obstruction of justice by false claims." },
            { sectionNumber: "411", description: "Misuse of court authority." },
            { sectionNumber: "412", description: "Legal repercussions for interfering with justice." },
            { sectionNumber: "413", description: "False representations in judicial contexts." },
            { sectionNumber: "414", description: "Corruption and fraud in court proceedings." },
            { sectionNumber: "415", description: "Failure to provide accurate evidence in court." },
            { sectionNumber: "416", description: "Tampering with judicial processes." },
            { sectionNumber: "417", description: "Contempt of judicial authority." },
            { sectionNumber: "418", description: "Obstructing legal processes with false evidence." },
            { sectionNumber: "419", description: "Legal consequences of obstructing court orders." },
            { sectionNumber: "420", description: "Interference with judicial authority." },
            { sectionNumber: "421", description: "Corruption and fraudulent practices in court." },
            { sectionNumber: "422", description: "Misrepresentation in court procedures." },
            { sectionNumber: "423", description: "Failure to comply with judicial orders." },
            { sectionNumber: "424", description: "Obstructing justice through illegal means." },
            { sectionNumber: "425", description: "Contempt and interference with judicial proceedings." },
            { sectionNumber: "426", description: "Legal repercussions for false claims in court." },
            { sectionNumber: "427", description: "Tampering with evidence in court." },
            { sectionNumber: "428", description: "Failure to follow judicial procedures." },
            { sectionNumber: "429", description: "Misuse of legal authority in judicial matters." },
            { sectionNumber: "430", description: "Corruption affecting court outcomes." },
            { sectionNumber: "431", description: "Obstructing justice with false information." },
            { sectionNumber: "432", description: "Contempt of court and legal consequences." },
            { sectionNumber: "433", description: "Failure to comply with court directives." },
            { sectionNumber: "434", description: "Corruption and abuse in judicial contexts." },
            { sectionNumber: "435", description: "Misrepresentation in legal documentation." },
            { sectionNumber: "436", description: "Interference with judicial processes." },
            { sectionNumber: "437", description: "Tampering with court proceedings." },
            { sectionNumber: "438", description: "Obstructing justice in legal procedures." },
            { sectionNumber: "439", description: "Legal consequences of contempt and obstruction." },
            { sectionNumber: "440", description: "Failure to adhere to judicial orders." },
            { sectionNumber: "441", description: "Corruption impacting judicial fairness." },
            { sectionNumber: "442", description: "False evidence and its legal ramifications." },
            { sectionNumber: "443", description: "Contempt of court and interference with justice." },
            { sectionNumber: "444", description: "Failure to follow legal directives." },
            { sectionNumber: "445", description: "Misuse of court authority and judicial procedures." },
            { sectionNumber: "446", description: "Obstructing justice through legal misconduct." },
            { sectionNumber: "447", description: "Legal consequences of fabricating evidence." },
            { sectionNumber: "448", description: "Contempt of court orders." },
            { sectionNumber: "449", description: "Failure to provide accurate information to courts." },
            { sectionNumber: "450", description: "Corruption and fraud in judicial matters." },
            { sectionNumber: "451", description: "Interference with judicial investigations." },
            { sectionNumber: "452", description: "False claims affecting court processes." },
            { sectionNumber: "453", description: "Contempt and legal consequences of obstruction." },
            { sectionNumber: "454", description: "Tampering with court evidence and records." },
            { sectionNumber: "455", description: "Misrepresentation in court and its legal impact." },
            { sectionNumber: "456", description: "Failure to comply with legal procedures." },
            { sectionNumber: "457", description: "Corruption in judicial administration." },
            { sectionNumber: "458", description: "Obstructing justice through false evidence." },
            { sectionNumber: "459", description: "Legal repercussions for interference with justice." },
            { sectionNumber: "460", description: "Contempt of court and its legal consequences." },
            { sectionNumber: "461", description: "Failure to adhere to judicial orders and procedures." },
            { sectionNumber: "462", description: "Corruption and fraudulent practices in judicial contexts." }
        ]
    },    
    {
        chapter: 18,
        chapterName: "Offences relating to Documents and Property Marks",
        sections: [
            { sectionNumber: "463", description: "Forgery" },
            { sectionNumber: "464", description: "Making a False Document" },
            { sectionNumber: "465", description: "Punishment for Forgery" },
            { sectionNumber: "466", description: "Forging Record of Court or Public Register, etc." },
            { sectionNumber: "467", description: "Forging Valuable Security, Will, etc." },
            { sectionNumber: "468", description: "Forging for the Purpose of Cheating" },
            { sectionNumber: "469", description: "Forging for the Purpose of Harm" },
            { sectionNumber: "470", description: "Definition of 'Counterfeit'" },
            { sectionNumber: "471", description: "Using as Genuine a Forged Document or Electronic Record" },
            { sectionNumber: "472", description: "Making or Possessing Counterfeit Seal, etc." },
            { sectionNumber: "473", description: "Making or Possessing Counterfeit Currency Note or Bank Note" },
            { sectionNumber: "474", description: "Having Possession of Counterfeit Currency Note or Bank Note" },
            { sectionNumber: "475", description: "Counterfeiting Coin" },
            { sectionNumber: "476", description: "Counterfeiting Currency Coin or Bank Note" },
            { sectionNumber: "477", description: "Falsification of Accounts" },
            { sectionNumber: "478", description: "Counterfeiting of Currency or Bank Notes" },
            { sectionNumber: "479", description: "Fabrication of False Evidence" },
            { sectionNumber: "480", description: "Using False Evidence" },
            { sectionNumber: "481", description: "Using as Genuine a Forged Document" },
            { sectionNumber: "482", description: "Forgery in Judicial Proceedings" },
            { sectionNumber: "483", description: "Making or Possessing Counterfeit Seal or Stamp" },
            { sectionNumber: "484", description: "Making or Possessing Counterfeit Currency or Bank Notes" },
            { sectionNumber: "485", description: "Counterfeiting of Currency or Bank Notes" },
            { sectionNumber: "486", description: "Making or Possessing Counterfeit Coin" },
            { sectionNumber: "487", description: "Using as Genuine a Forged Document" },
            { sectionNumber: "488", description: "Making or Possessing Counterfeit Coin" },
            { sectionNumber: "489A", description: "Counterfeiting currency notes or bank notes" },
            { sectionNumber: "489B", description: "Using as genuine, forged or counterfeit currency notes or bank notes" },
            { sectionNumber: "489C", description: "Possession of forged or counterfeit currency notes or bank notes" },
            { sectionNumber: "489D", description: "Making or possessing instruments or materials for counterfeiting" },
            { sectionNumber: "489E", description: "Definitions related to currency notes and bank notes" }
        ]
    },    
    {
        chapter: 19,
        chapterName: "Criminal Breach of Contracts of Service",
        sections: [
            { sectionNumber: "491", description: "Breach of contract to attend on and supply wants of helpless person." },
            { sectionNumber: "491", description: "Punishment for Criminal Breach of Contract of Service" },
            { sectionNumber: "492", description: "Breach of Contract by a Public Servant" }
        ]
    },
    {
        chapter: 20,
        chapterName: "Of Offenses Relating to Marriage",
        sections: [
            { sectionNumber: "493", description: "Cohabitation caused by a man deceitfully inducing a belief of lawful marriage" },
            { sectionNumber: "494", description: "Marrying again during the lifetime of a husband or wife" },
            { sectionNumber: "495", description: "Marrying again during the lifetime of a husband or wife with concealment of previous marriage" },
            { sectionNumber: "496", description: "Marriage ceremony fraudulently performed without lawful authority" },
            { sectionNumber: "497", description: "Adultery" },
            { sectionNumber: "498", description: "Enticing or taking away or detaining with criminal intent a married woman" }
        ]
    },
    {
        chapter: '20A',
        chapterName: "Of Cruelty by Husband or Relatives of Husband",
        sections: [
            { sectionNumber: "498A", description: "Husband or relative of husband of a woman subjecting her to cruelty" }
        ]
    },    
    {
        chapter: 21,
        chapterName: "Of Defamation",
        sections: [
            { sectionNumber: "499", description: "Defamation" },
            { sectionNumber: "500", description: "Punishment for Defamation" },
            { sectionNumber: "501", description: "Printing or Engraving of Defamatory Matter" },
            { sectionNumber: "502", description: "Sale of Defamatory Matter" }
        ]
    },    

    {
        chapter: 22,
        chapterName: "Of Criminal Intimidation, Insult and Annoyance",
        sections: [
            { sectionNumber: "503", description: "Criminal Intimidation" },
            { sectionNumber: "504", description: "Intentional Insult with Intent to Provoke Breach of the Peace" },
            { sectionNumber: "505", description: "Statements Conducive to Public Mischief" }
        ]
    },
    {
        chapter: 23,
        chapterName: "Attempts to Commit Offenses",
        sections: [
            { sectionNumber: "511", description: "Punishment for attempting to commit offenses punishable with imprisonment for life or other imprisonment." }
        ]
    }
];
